---
apiVersion: v1
kind: Route
metadata:
  name: web-nas
spec:
  host: web-nas.apps.vaultocp3a.cloud.wwtatc.local 
  to:
    kind: Service
    name: web-nas

---
apiVersion: v1
kind: Service
metadata:
  name: web-nas
  labels:
    app: web-nas
spec:
  ports:
  - port: 80
    name: web
    targetPort: 8080
  selector:
    app: web-nas

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-nas
spec:
  selector:
    matchLabels:
      app: web-nas # has to match .spec.template.metadata.labels
  serviceName: "web-nas"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: web-nas # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ontap-nas"
      resources:
        requests:
          storage: 1Gi


---
apiVersion: v1
kind: Route
metadata:
  name: web-san
spec:
  host: web-san.apps.vaultocp3a.cloud.wwtatc.local
  to:
    kind: Service
    name: web-san

---
apiVersion: v1
kind: Service
metadata:
  name: web-san
  labels:
    app: web-san
spec:
  ports:
  - port: 80
    name: web
    targetPort: 8080
  selector:
    app: web-san

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-san
spec:
  selector:
    matchLabels:
      app: web-san # has to match .spec.template.metadata.labels
  serviceName: "web-san"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: web-san # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ontap-san"
      resources:
        requests:
          storage: 1Gi